name: Scala CI

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Install mill
        run: sudo curl -L https://github.com/com-lihaoyi/mill/releases/download/0.9.5/0.9.5 > /usr/local/bin/mill && sudo chmod +x /usr/local/bin/mill
      - name: Build telegram library
        run: sbt buildTelegramLibrarySnapshot
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and push
        run: |
          sbt docker:publishLocal
          docker tag nakayoshi:latest  soramitsu/nakayoshi:latest
          docker tag nakayoshi:latest  soramitsu/nakayoshi:0.1.3 
          docker push soramitsu/nakayoshi:latest
          docker push soramitsu/nakayoshi:0.1.3
